# tolerance is an optional field
# defaults to 10%

topics:
  - name: /visual_slam/tracking/vo_pose_covariance
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    expected_rate: 15.0
    tolerance: 0.10 
  - name: /camera/infra1/camera_info
    type: sensor_msgs/msg/CameraInfo
    expected_rate: 15.0
    tolerance: 0.10 
    window: 30
